### ISSUE TITLE
Additional type safety

### ISSUE THREAD

**Issue by japgolly** [chandu0101/scalajs-react-components#1]
Hey mate. Instead of using strings it'd be great to have types for bootstrap enums and such.

Eg. in this, one could easily mistype "prmary"

``` scala
bootStrap.Button(bsStyle = "primary")("Primary")
```

You could add types like this:

``` scala
sealed abstract class BsStyle(val name: String)
object BsStyle {
  case object Primary extends BsStyle("primary")
  case object Default extends BsStyle("default")
  // ...
}
```

So that usage becomes nice and type-safe like this:

``` scala
bootStrap.Button(BsStyle.Primary)("Primary")
```

**Comment by chandu0101** [comment]
cool , nice idea , this will solve one of props type too ..., i'll implement this 

Thank You
Chandra
