### ISSUE TITLE
JSMacro causes StackOverflowError when compiling certain classes

### ISSUE THREAD

**Issue by rleibman** [chandu0101/scalajs-react-components#100]
If you comment-in Dropdown in SuiLibrary, you get the following:

error] [E6] core/target/scala-2.12/src_managed/main/chandu0101/scalajs/react/components/semanticui/SuiDropdown.scala
[error]      exception during macro expansion: java.lang.StackOverflowError
[error]      L176:    val props = JSMacro[SuiDropdown](this)
[error]      L176:                       ^

Note that I've made a lot of other changes to get other things to work before I got to this result, so you may not be able to see it immediately.

**Comment by oyvindberg** [comment]
When i hacked it into generating code (added a bunch of callbacks), i got props like these:
```scala
defaultValue:         js.UndefOr[Double | String | js.Array[js.Any] |  | String | Double] 
```
Notice the syntax error with a missing type there. I'm fairly sure the immediate issue is that the props parser is not clever enough to understand these things:
```javascript
  defaultValue: PropTypes.oneOfType([PropTypes.number, PropTypes.string, PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number]))])
```

For the SOE I'm pretty sure it can be fixed by this small patch:
```diff
     def flattenUnion(tpe: Type): List[Type] =
-      if (tpe <:< typeOf[js.|[_, _]])
+      if (tpe == NoType) Nil
+      else if (tpe <:< typeOf[js.|[_, _]])
         flattenUnion(tpe.typeArgs(0)) ++ flattenUnion(tpe.typeArgs(1))
       else List(tpe)
```

Can you test it? 

For the props parsing itself we should make it a lot more robust. I have thoughts as to how, but i think it can quickly require a bit of work. Is it something that you envision working on @rleibman ?

**Comment by rleibman** [comment]
I just tried it, Sorry, no, it doesn't fix it... this particular issue I had already addressed (in a different way, granted) in the 1.1.0 branch.

**Comment by rleibman** [comment]
As for working on the parser... I'd like to hear your thoughts on it. I don't have a lot of time to hack lately, and I've been focusing on getting my own personal project (a recipe manager) that uses this library, which drives the changes I've been making to it.

**Comment by oyvindberg** [comment]
Haha, got it! I found your 1.1.0-branch now and tested it. It turns out that japgolly has found a way to declare ReactNode as a recursive type alias in scalaja-react 1.2 :cake: .

I'll... find a way :)

**Comment by rleibman** [comment]
Thank you, that worked and I managed to pull in a few more Sui components that I needed. I do get a warning:
```
[warn]  [E21] core/target/scala-2.12/src_managed/main/chandu0101/scalajs/react/components/semanticui/SuiDropdown.scala
[warn]        The outer reference in this type test cannot be checked at run time.
[warn]        L176:    val props = JSMacro[SuiDropdown](this)
[warn]        L176:                       ^
```
I haven't tested to see if it'll be a problem, but for now, it compiles.
