### ISSUE TITLE
installMuiContext

### ISSUE THREAD

**Issue by sahataba** [chandu0101/scalajs-react-components#11]
Hi,

how can i install mui context.

i'm getting this error while trying to compile demo.

value hackSpec is not a member of japgolly.scalajs.react.ReactComponentB.PSBN[chandu0101.scalajs.react.components.demo.pages.MuiPage.Props,Unit,Unit]
[error] possible cause: maybe a semicolon is missing before `value hackSpec'?
[error]     .hackSpec(materialui.installMuiContext)

Rudolf

**Comment by chandu0101** [comment]
hi ,
current scalajs-react (0.9) doesn't support it . 

clone this fork `git clone -b unsfasespec https://github.com/chandu0101/scalajs-react/` and publish locally using  `sbt publishLocal`

wav already pushed a PR to master https://github.com/japgolly/scalajs-react/pull/144 
once its done ,we don't need this extra work ( i'll also  push scalajs-react-components to maven central) 

Thank You
Chandra

**Comment by chandu0101** [comment]
ok fix is in scalajs-react master now ,it'll be available when next version published.
