### ISSUE TITLE
material-ui 0.9.2 released

### ISSUE THREAD

**Issue by zlangbert** [chandu0101/scalajs-react-components#15]
https://github.com/callemall/material-ui/blob/master/CHANGELOG.md

**Comment by chandu0101** [comment]
@zlangbert  do you want 0.9.2 in initial release of scalajs-react-components ( planned for 24th ) ?

**Comment by zlangbert** [comment]
Sounds good to me. I'll try to finish the update tonight

**Comment by chandu0101** [comment]
@zlangbert  do you want me to postpone date ?

Edit : postponed to 28th :)

**Comment by oyvindberg** [comment]
we're up to 0.13.4 now, so closing this :)
