### ISSUE TITLE
Easier JS dependencies

### ISSUE THREAD

**Issue by ghost** [chandu0101/scalajs-react-components#18]
I'm not sure if you have plans to solve this but it would be nice if it was easier to use the javascript dependencies in this project.

Ideally it would be a webjar specified using jsDependencies. I'm not sure if that is possible or not and it may be that there would be multiple webjars for each each dependency? Other problems are, how do you even create the correct webjars? (I noticed there is material-ui webjar but it is an npm webjar, so I assume that won't work.)

This would be nice because everything would end up in scalajs -jsdeps.js

Anyway I needed something that worked now. I looked for existing sbt wrappers around javascript build tools but there doesn't really seem to be much out there.

I ended up creating a small sbt task that integrates with the sbt-web pipeline and calls out to npm (and webpack). I've only tested Material UI.

**Task key**

``` scala
val packageReactComponents = TaskKey[Seq[File]]("packageReactComponents", "Package Scala.js React Components")
```

**Project settings**

``` scala
    packageReactComponents := {
      val filename = "sjs-components.js"

      val outPath = WebKeys.webTarget.value / "sjscomponents"
      val outFile = outPath / filename
      val workingDir = baseDirectory.value

      if ( ! outFile.exists()) {
        val commandPrefix = sys.props("os.name").toLowerCase match {
          case os if os.contains("win") => Seq("cmd", "/C")
          case _ => Seq()
        }

        val installCommand = commandPrefix ++ Seq("npm", "install")
        println(s"${installCommand.mkString(" ")}")
        Process(installCommand, workingDir) !!

        val runCommand = commandPrefix ++ Seq("npm", "run", "build", "--", "--output-file", filename, "--output-path", outPath.getAbsolutePath)
        println(s"Creating $filename [${runCommand.mkString(" ")}]")
        Process(runCommand, workingDir) !!
      }

      Seq[File](outFile)
    },
    (sourceGenerators in Assets) <+= packageReactComponents
```

**main.js**

``` javascript
var mui = require("material-ui"),
    injectTapEventPlugin = require('react-tap-event-plugin');

injectTapEventPlugin();

window.mui = mui;
```

**package.json**

``` json
{
  "name": "",
  "version": "0.1.0",
  "description": "",
  "scripts": {
    "build": "webpack --config webpack.config.js"
  },
  "devDependencies": {
    "webpack": "^1.9.10"
  },
  "dependencies": {
    "material-ui": "^0.9.0",
    "react-geomicons": "^2.0.4",
    "react-select": "^0.5.1",
    "react-tagsinput": "^1.3.5",
    "react-tap-event-plugin": "^0.1.7",
    "svg-loader": "0.0.2"
  }
}
```

**webpack.config.js**

``` javascript
'use strict';

var webpack = require('webpack');
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;

module.exports = {
    entry: {
        mainpage: './main.js'
    },
    output: {
    },
    externals: {
      "react": "React",
      "react/addons": "React"
    },
    plugins: [
        new webpack.NoErrorsPlugin(),
        new CommonsChunkPlugin({
            name: "mainpage"
        })
    ]
};
```

Note the use of externals here, that is because I am depending on the React webjar which already ends up in -jsdeps.js

I'm not sure if there will end up being any gotchas with this (ie dependency ordering issues). (Not sure if it will work long term). Maybe I'll end up not using the React webjar and bundle the one with webpack.

Finally I just include the generated js in my play template

``` scala
<script src="@routes.Assets.versioned("sjs-components.js")"></script>
```

I don't know if there is a better way. I think the tooling in this area needs some work still if it has to be done through npm could watch this space and use something like grunt: https://github.com/sbt/sbt-web/issues/27

I'm not that familiar with these tools though.

**Comment by chandu0101** [comment]
indeed its a painful issue at the moment . not only for this project, any scala.js project that interop with javascript . 

Its out of scope for this project ,it should belong to sbt-web or sbt plugins/wrappers or scala.js jsDeps .... .

I prefer using js world build tools for managing javascript dependencies and builds.. and sbt for scala.js compilation so that we will get best from both worlds !, this approach looks like more work at the begining as there is a learning curve but in long run it'll pay off! 

Caution : I have very limited knowledge in sbt/sbt-web so i may be wrong

**Comment by ghost** [comment]
Fair enough. I guess it really does boil down to needing a bridge from js build tools to something like sbt-web which isn't something that should be solved by this project necessarily. It was just quite painful getting started with the project when I'm used to not having to use anything outside sbt.

This issue may just be a useful reference for a quick hack to get started using sbt-web for someone else.

 Hopefully someone writes a nice js build tool wrapper in sbt-web, in which case it could be documented here in the future.

**Comment by chandu0101** [comment]
> It was just quite painful getting started with the project when I'm used to not having to use anything outside sbt

totally agree , many people in gitter channel also  expressed same concern , wish i have powers to make  a smooth path :(
