### ISSUE TITLE
MUI RadioButtonGroup onChange property seems to have the wrong type

### ISSUE THREAD

**Issue by enijns** [chandu0101/scalajs-react-components#20]
When trying to use the onChange property of the radiobuttongroup I'm getting the following error:

```
Uncaught scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: bladiebla is not an instance of java.lang.Boolean
```

I'm using the following code:

```
MuiRadioButtonGroup(onChange = {(e: ReactEventI, b: Boolean) => ???}, ...)(children)
```

The documentation from http://callemall.github.io/material-ui/#/components/switches contains:
"Callback function that is fired when a radio button has been clicked. Returns the event and the value of the radio button that has been selected."

I believe 'the value of a radio button' is a String instead of a Boolean? Is that the cause of this error?

**Comment by chandu0101** [comment]
yes it should be string ,thanks for finding and reporting .could you please send a PR if possible ..

**Comment by enijns** [comment]
I'll try to send a pull request

**Comment by enijns** [comment]
https://github.com/chandu0101/scalajs-react-components/pull/21
