### ISSUE TITLE
cleaning up comments/formatting/printlns

### ISSUE THREAD

**Issue by chandu0101** [chandu0101/scalajs-react-components#25]
cleanup core module

**Comment by oyvindberg** [comment]
hey, i have some time to use on this project again now. Between japgollys newest changes and your cleanup commits im pretty much starting over with the scalajs-react 0.10 changes. I'm opening a separate discussion issue for that soon, but for now i made some further cleanup commits [here](https://github.com/elacin/scalajs-react-components/commits/cleanups). 

Tell me which ones you like and which you dont like, I'll PR what you think makes sense - It's all search/replace, which I'm starting to become good at hehehe

**Comment by chandu0101** [comment]
@elacin  all PR's makes sense and looks good please send a PR :+1:  , btw i just made macros public see if you can modify for u r use case, let me know if anything unclear :)

**Comment by oyvindberg** [comment]
done long time ago, closing
