### ISSUE TITLE
scalajs-react 0.10

### ISSUE THREAD

**Issue by oyvindberg** [chandu0101/scalajs-react-components#29]
So, I have some questions for how to do this, figured i would make a discussion issue for it.
- Some of the components still written in scala (`ReactDraggable`, `ReactTable`, `ReactTreeView`, for example) require quite a lot of attention. Are these scala ports of javascript code? Is this a good time to make them into wrappers like materialui?
- I'm happy you made the macro thingie, it makes a lot of boilerplate go away. I'm pretty sure i can hack that into doing the `Callback` rewriting we will need to do (adding `runNow()` to all functions passed into javascript land). However, this requires a dependency upon scalajs-react, whereas the macro project doesnt have it now. Should we include that dependency there? or copy the macros into this project?

I have a few more points, but let's decide these two first.

**Comment by chandu0101** [comment]
> Are these scala ports of javascript code?

ReactTable, ReactTreeView are not, but ReactDraggable is , recently  @coreyauger  made some improvements to ReactDraggable  so i'll leave the decision to him .

> However, this requires a dependency upon scalajs-react, whereas the macro project doesnt have it now. Should we include that dependency there? or copy the macros into this project?

second option :+1:

**Comment by coreyauger** [comment]
Only thing I added to Draggable were mobile events.  None of the drabbalbe events were firing on mobile.  Thanks .
