### ISSUE TITLE
Demo build instructions don't work on MS-Windows

### ISSUE THREAD

**Issue by tpdi** [chandu0101/scalajs-react-components#33]
Demo build instructions are:

cd demo
sbt ~fastOptJS
//open a new terminal tab/window
npm install
npm start
//open in browser
http://localhost:8090/

fastOptJS works from the parent directory, not from demo. For me it works better from interactive sbt (sbt, then fastOptJS), rather than from the command line ("sbt fastOptJS").

There are issues with webpack on MS-Windows; it runs but does not serve the directory. 

Here's one possible workaround: Instead of the  npm install/npm start steps, run 

python -m SimpleHTTPServer 

in the demo subdirectory. Of course, you must have python installed to do this.

**Comment by chandu0101** [comment]
thanks for reporting , did you tried in cigwin shell or plain dos cmd ?

**Comment by tpdi** [comment]
A good question. I tried it in a Git for Windows bash shell.

However, I get the same result in cmd shell. I should note, though, that I did explicitly install node-gyp (which may be what doesn't work under windows) in an attempt to solve the issue.

**Comment by oyvindberg** [comment]
i'll change the sbt command to `sbt demo/fastOptJS` before `cd demo`, that should fix the first. for the webpack issues on windows i have no idea

**Comment by workingDog** [comment]
I'm also having problems building the demo and webpack on macosx 10.12.1.
I get the following errors (also when using: npm start):

webpack --config webpack.config.prod.js
Hash: 2a63ed6555632f127952
Version: webpack 1.13.3
Time: 28717ms
                               Asset     Size  Chunks             Chunk Names
                     index-bundle.js   737 kB       0  [emitted]  index
386a2e9718c30b5bccde524c62c3a1ed.png  28.4 kB          [emitted]
f6b67456a1496d917500f40cb9af7256.png  25.5 kB          [emitted]
7adec32865b47c15c268986d7470ec83.png  38.8 kB          [emitted]
255c8317b85706383e68cb14da22372d.png  17.8 kB          [emitted]
a0d06231f0715a24c41691d96c479b23.png  14.5 kB          [emitted]
3ebbc1f9e62e1a745bb4d0a96eca2bb0.png  10.8 kB          [emitted]
3d144ac00eb77bd85fcc780103f06e63.png  22.1 kB          [emitted]
555643527c5af9c5a612bbbad5e3ee41.png  11.9 kB          [emitted]
febdbb7ed7aead8d82bcafb9f232e179.png  21.6 kB          [emitted]
               material_ui-bundle.js   1.2 MB       1  [emitted]  material_ui
            react_infinite-bundle.js   204 kB       2  [emitted]  react_infinite
              elemental_ui-bundle.js   155 kB       3  [emitted]  elemental_ui
          react_geom_icons-bundle.js  8.77 kB       4  [emitted]  react_geom_icons
               react_slick-bundle.js  24.8 kB       5  [emitted]  react_slick
              react_select-bundle.js  52.3 kB       6  [emitted]  react_select
          react_tags_input-bundle.js   9.2 kB       7  [emitted]  react_tags_input
             react_spinner-bundle.js  1.77 kB       8  [emitted]  react_spinner
   [0] ./bundles/elemental-ui.js 104 bytes {3} [built]
   [0] ./bundles/index.js 1.19 kB {0} [built]
   [0] ./bundles/material-ui.js 160 bytes {1} [built]
   [0] ./bundles/react-geom-icons.js 95 bytes {4} [built]
   [0] ./bundles/react-infinite.js 71 bytes {2} [built]
   [0] ./bundles/react-select.js 125 bytes {6} [built]
   [0] ./bundles/react-slick.js 119 bytes {5} [built]
   [0] ./bundles/react-spinner.js 110 bytes {8} [built]
   [0] ./bundles/react-tags-input.js 138 bytes {7} [built]
    + 2007 hidden modules

ERROR in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in /Users/ringo/test5/scalajs-react-components-master/demo/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-37

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in /Users/ringo/test5/scalajs-react-components-master/demo/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-56

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginUtils' in /Users/ringo/test5/scalajs-react-components-master/demo/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPropagators' in /Users/ringo/test5/scalajs-react-components-master/demo/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/SyntheticUIEvent' in /Users/ringo/test5/scalajs-react-components-master/demo/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/ViewportMetrics' in /Users/ringo/test5/scalajs-react-components-master/demo/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58

**Comment by oyvindberg** [comment]
Thanks for reporting, @workingDog. Something has apparently changed with `react-tap-event-plugin`, and thanks to the endless wonders of npm, that was pulled into this project (google for details, was easy to find).

i'll fix it in #76
