### ISSUE TITLE
remove bootstrap facade from repo ? 

### ISSUE THREAD

**Issue by chandu0101** [chandu0101/scalajs-react-components#34]
All,
anyone using bootstrap wrapper ?  please let me know your  opinion on dropping bootstrap in future versions!

**Comment by oyvindberg** [comment]
It would be very, very useful to have a working library for bootstrap components. These components here do not look finished nor tested, plus there is no demo application like there is for materialui and so on, so there is quite a lot of work!

How about we extract them into a repo of it's own, split all the components into individual files, and write a short readme saying it needs more work before it's ready to encourage people to contribute?

**Comment by chandu0101** [comment]
> How about we extract them into a repo of it's own,

we already have a couple of libs out there ..

https://github.com/weiyinteo/scalajs-react-bootstrap
https://github.com/aparo/scalajs-react-extra/tree/master/react-bootstrap/src/main/scala/sjs

**Comment by oyvindberg** [comment]
Oh, i should have know. In that case 👍

**Comment by chandu0101** [comment]
@elacin  thanks for feedback :) 

@bpressure recently u sent a PR to reactbootstrap ,so are you using them ? can we delete this half-baked code from our repo ?

**Comment by oyvindberg** [comment]
removed this now
