### ISSUE TITLE
(Upstream) bug in MuiTimePicker

### ISSUE THREAD

**Issue by tpdi** [chandu0101/scalajs-react-components#35]
Passing js.undefined or null as the defaultTime for an MuiTimePicker results in 

Uncaught TypeError: Cannot read property 'getHours' of null

when the time picker dialog is shown, iff the TimePicker format is "ampm".

Steps to reproduce:
render any of 
MuiTimePicker()(),
MuiTimePicker(defaultTime = js.undefined)(),
MuiTimePicker(defaultTime = null)()

then trigger dialog show.

Why pass defaultTime as null? To show no time display at all. 

Workaround: pass new Date(),or set time format to TWENTY_FOUR_HOUR. However both workarounds show a time (x:xx or 12:00am) rather than leaving the input blank, as desired.

**Comment by chandu0101** [comment]
thanks for reporting , can you please test same scenario on original material-ui https://github.com/callemall/material-ui ..

**Comment by tpdi** [comment]
I did, this bug is not evident in their latest example. I suspect you could update the material-ui.js version to fix it.

**Comment by chandu0101** [comment]
cool ok , i'll take care then .. .

**Comment by oyvindberg** [comment]
so i suppose this will be fixed with the new version now, optimistically closing :)
