### ISSUE TITLE
Order of arguments in MUI case classes

### ISSUE THREAD

**Issue by tpdi** [chandu0101/scalajs-react-components#36]
The order of arguments in the Mui component case classes seems arbitrary. What's the reason behind the ordering you use?

**Comment by chandu0101** [comment]
those are generated from material-ui PropTypes , i am happy to take a PR with correct order :), If you're up for this task then please add new fields that came after 0.9.1!

**Comment by oyvindberg** [comment]
after regeneration i ended up with the following:
- props with documentation
- event handlers
- all other props without documentation
  documentation is pulled from material-ui itself, we are not writing it ourselves.

If there are strong opinions we could change that of course
