### ISSUE TITLE
MUIDatePicker can be a controled componenet, and has an implicit property of `value`

### ISSUE THREAD

**Issue by tpdi** [chandu0101/scalajs-react-components#38]
Material-ui's DatePicker looks for `value` (and `valueLink`) in its props, even though these are not listed in its propTypes.

However, DatePicker uses `props.hasOwnProperty('value')` to test whether the component is controlled, so an UndefOr[Date] might not be the appropriate way to add `value` to MuIDatePicker. 

Edit: if `UndefOr` are added to a js.Dynamic using foreach, it should be OK.

For what it's worth, TimePicker does not support the value property (!)

**Comment by oyvindberg** [comment]
value prop is now added to Mui[Time|Date]Picker
