### ISSUE TITLE
elemental-ui modal demo not working 

### ISSUE THREAD

**Issue by chandu0101** [chandu0101/scalajs-react-components#48]
`Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's`render`method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

@rleibman  can you please look into this ..

**Comment by oyvindberg** [comment]
ive noticed and fixed it locally, we just need to remove whatever `ref`s is set in there and it works

**Comment by oyvindberg** [comment]
Fixed in #49
