### ISSUE TITLE
createFactory vs createElement

### ISSUE THREAD

**Issue by mblund** [chandu0101/scalajs-react-components#78]
I'm looking at your example 
```
 def apply(children : ReactNode*) = {
     val f = React.asInstanceOf[js.Dynamic].createFactory(js.Dynamic.Global.AwesomeJSComp) // access real js component , make sure you wrap with createFactory (this is needed from 0.13 onwards)
     f(toJS, children.toJsArray).asInstanceOf[ReactComponentU_]
    }
```

and compare it to the current react documentation of the createFactory function https://facebook.github.io/react/docs/react-api.html#createfactory
 

> This helper is considered legacy, and we encourage you to either use JSX or use React.createElement() directly instead.

I'm trying out createElement https://facebook.github.io/react/docs/react-api.html#createelement

```
def apply(children: ReactNode*): ReactComponentU_ = {
    if (children.isEmpty)
      React.asInstanceOf[js.Dynamic].createElement(comp, propsToJs).asInstanceOf[ReactComponentU_]
    else if (children.size == 1)
      React.asInstanceOf[js.Dynamic].createElement(comp, propsToJs,children.head ).asInstanceOf[ReactComponentU_]
    else
      React.asInstanceOf[js.Dynamic].createElement(comp, propsToJs, children.toJsArray ).asInstanceOf[ReactComponentU_]
  }
```
and it seems to work fine.

What is your thought about this?

**Comment by chandu0101** [comment]
@mblund  https://discuss.reactjs.org/t/best-way-to-create-reactelements-without-jsx/2042

**Comment by mblund** [comment]
ok, thanks for the quick answer. I think I will go with createElement then. Both consider that "consider legacy" comment in the docs and that "createFactory" feels like a heavy operation to me.

**Comment by chandu0101** [comment]
yeah i also suggest `createElement` , btw you don't need that children size logic , just do 

```scala
 React.asInstanceOf[js.Dynamic].createElement(comp, propsToJs, children :_*).asInstanceOf[ReactComponentU_] 
```

**Comment by mblund** [comment]
thx, but I get
```
[error] applyDynamic does not support passing a vararg parameter
[error]     React.asInstanceOf[js.Dynamic].createElement(comp, propsToJs, children :_*).asInstanceOf[ReactComponentU_]
```
when I try that
