### ISSUE TITLE
Semantic UI Typings

### ISSUE THREAD

**Issue by clifflo** [chandu0101/scalajs-react-components#82]
Hi in the readme I cannot find Semantic UI but in the source codes I can. So do I need to have Semantic UI Javascript files in order to make that work?

Also in the source files they are generated. So what sort of tools are you using to generate those files? Is that Typescript to Scala?

**Comment by chandu0101** [comment]
@clifflo  

>in the readme I cannot find Semantic UI 
 its my mistake  :( 

>So do I need to have Semantic UI Javascript files in order to make that work?

yes check demo app for example

>So what sort of tools are you using to generate those files? 

https://github.com/chandu0101/semantic-ui-facade-generator

recently i moved my focus to sri , @oyvindberg  is maintaining this repo now. feel free to send PR's :)

**Comment by clifflo** [comment]
Thanks for your reply. So with regard to your semantic-ui-facade-generator, does it mean that there is no tool for automatically parsing the typescript definition that's why you have to write that yourself? If it is so then as I am going to write a tool to summarize the props from different react components and then you may convert that to typescript or flowtype or scalajs as a result.

**Comment by oyvindberg** [comment]
Generator will be included in project with #89
