### ISSUE TITLE
Create a wrapper for react-split-pane

### ISSUE THREAD

**Issue by atooni** [chandu0101/scalajs-react-components#88]

**Comment by oyvindberg** [comment]
I dont have the bandwidth to contribute components i dont use myself. PR would be most welcome :gift:

**Comment by atooni** [comment]
That was the plan ;). I do have a rudimentary wrapper, the ticket is a reminder for myself to take some time to create a PR.

**Comment by zyl520** [comment]
我的不能拉动,这是什么问题
