### ISSUE TITLE
Issue with react-bootstrap

### ISSUE THREAD

**Issue by landlockedsurfer** [chandu0101/scalajs-react-components#9]
Hi!
I'm struggling to get scalajs-react going with react-bootstrap from https://github.com/chandu0101/scalajs-react-components
Using Chrome I'm getting this error on the console:
`Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined`
Did anybody encounter the same issue? I've set up a repo @ https://github.com/landlockedsurfer/scalajs-react-bootstrap to help reproduce the error.

**Comment by chandu0101** [comment]
Hi ,
  reactbootstrap doesn't work :( , thats why its not included in demos . I'll remove it when i release first version of scalajs-react-components . If you want scalajs-react-bootstrap then use this library 

https://github.com/weiyinteo/scalajs-react-bootstrap

**Comment by landlockedsurfer** [comment]
Thanks for the quick reply and the link!

Is your repository the place to put facades to existing React components? I.e. if one has followed the steps you describe in
https://github.com/chandu0101/scalajs-react/blob/master/InteropWithThirdPartyComponents.md
can one send you a pull request to add it to your repo @ https://github.com/chandu0101/scalajs-react-components ?

**Comment by chandu0101** [comment]
absolutely dude , please keep em coming . one thing i am wondering is how about having a common prefix/suffix for thirdparty comp ? 

Example : **ReactJS**TableComponent
**JS**TableComponent 
TableComponent**JS**
or .. ?

**Comment by landlockedsurfer** [comment]
Unfortunately I'm not quite there yet thinking about a good naming schema for the React facades. :-) I'm still stuck with creating a facade on this component https://github.com/olahol/react-tagsinput.
I've created another repo @ https://github.com/landlockedsurfer/scalajs-react-facade-test to reproduce the problem. Again, got the `Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined` error.
Did you ever have a similar issue?
Thanks.

**Comment by chandu0101** [comment]
you're using react 0.13 , it requires createFactory gaurd for js components

``` scala
 // we should update scalajs-react core for over loaded method of createFactory to accept js.Dynamic/object , till then cast it to js.Dynamic and then call createFactory
  val f =  React.asInstanceOf[js.Dynamic].createFactory(js.Dynamic.global.ReactTagsInput) // access real js component
```

I'll update doc too , thank you for bringing it up :)

**Comment by landlockedsurfer** [comment]
Thanks a ton... working nicely now!
Have seen your pull request to the `japgolly/scalajs-react` repo. Your page on third party component interoperability really belongs there.
I wonder how a painless management of ScalaJS React facades and the underlying Javascript versions could look like.

**Comment by chandu0101** [comment]
> I wonder how a painless management of ScalaJS React facades and the underlying Javascript versions could look like.

sorry for delay(intentional though) , it looks like its super easy if we use js-world tools. currently i am using webpack in demo module its freaking awesome.

**Comment by landlockedsurfer** [comment]
Congrats on the release of 0.1.0!
 Thanks for the pointer on webpack. Indeed webpack seems the to be the best choice to deal with the Javascript bindings, also considering npm and webpack seems to b the most popular choice in Javascript React land.
